[tool.poetry]
name = "txtadv_nightly"
version = "110105103104116108121110105103104116108121.0"
description = "The nightly version of txtadv, a feature-rich text adventure library!"
readme = {file = "txtadv_nightly/BUILD_DESC.md", content-type = "text/markdown"}
authors = ["sdft <averse.abfun@gmail.com>"]
packages = [
    { include = "txtadv-nightly" }
]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"