[tool.poetry]
name = "tapy"
version = "1.0-beta2"
description = ""
authors = ["sdft <averse.abfun@gmail.com>"]
packages = [
    { include = "tapy" }
]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"